#!/bin/sh
#/etc/init.d/shot-mp
#service script for MetaPixelCamera

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
MPDir=/home/pi/MetaPixelCamera

case "$1" in
start)
exec forever --sourceDir=$MPDir -p $MPDir shotMP.js  
;;
stop)
exec forever stop --sourceDir=$MPDir shotMP.js
;;
*)
echo "Usage: /etc/init.d/shot-mp {start|stop}"
exit 1
;;
esac
exit 0
